# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_audit', '0002_auto_fix_field_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
